version: 2.1

commands:
  influxdb-onboarding:
    steps:
      - run:
          name: "Post onBoarding request to InfluxDB 2"
          command: ./scripts/influxdb-onboarding.sh
  prepare:
    description: "Prepare environment to tests"
    steps:
      - checkout
      - influxdb-onboarding
  client-test:
    description: "Run tests"
    parameters:
      python-image:
        type: string
      enabled-ciso-8601:
        type: boolean
    steps:
      - restore_cache:
          name: Restoring Pip Cache
          keys:
            - &cache-key pip-cache-v9-<< parameters.python-image >>-<< parameters.enabled-ciso-8601 >>-{{ checksum "requirements.txt" }}-{{ checksum "test-requirements.txt" }}-{{ checksum "extra-requirements.txt" }}-{{ checksum "ciso-requirements.txt" }}
            - pip-cache-v9-<< parameters.python-image >>-<< parameters.enabled-ciso-8601 >>-
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
      - run:
          name: "Running tests"
          command: ./scripts/ci-test.sh
      - save_cache:
          name: Saving Pip Cache
          key: *cache-key
          paths:
            - ".venv"
            - "~/.cache/pip"
            # - "/usr/local/lib/python3.8/site-packages"
            # - "/usr/local/lib/python3.7/site-packages"
            # - "/usr/local/lib/python3.6/site-packages"
            - "/usr/local/lib/site-python"
          when: always
jobs:
  tests-python:
    parameters:
      python-image:
        type: string
        default: &default-python "circleci/python:3.6-buster"
      influxdb-image:
        type: string
        default: "influxdb:2.0.0-rc"
      enabled-ciso-8601:
        type: boolean
        default: true
    docker:
      - image: << parameters.python-image >>
        environment: # environment variables for primary container
          PIPENV_VENV_IN_PROJECT: true
          ENABLED_CISO_8601: << parameters.enabled-ciso-8601 >>
      - image: quay.io/influxdb/<< parameters.influxdb-image >>
        environment:
          INFLUXD_HTTP_BIND_ADDRESS: :8086
    steps:
      - prepare
      - client-test:
          python-image: << parameters.python-image >>
          enabled-ciso-8601: << parameters.enabled-ciso-8601 >>
      - store_test_results:
          path: test-reports
      - run:
          name: "Collecting coverage reports"
          command: bash <(curl -s https://codecov.io/bash) -f ./coverage.xml || echo "Codecov did not collect coverage reports"
  check-code-style:
    docker:
      - image: *default-python
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: Checks style consistency across sources.
          command: |
            pip install flake8 --user
            flake8 influxdb_client/
  check-twine:
    docker:
      - image: *default-python
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: Checks that the description will render correctly on PyPI.
          command: |
            pip install twine --user
            python setup.py sdist bdist_wheel
            twine check dist/*
  check-docstyle:
    docker:
      - image: *default-python
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: Checks compliance with Python docstring convention.
          command: |
            pip install pydocstyle --user
            pydocstyle --count influxdb_client
  check-aws-lambda-layer:
    docker:
      - image: docker:19
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Create Archive to upload as a custom Lambda Layer
          command: |
            cd docker/aws_lambda_layer
            docker build -t lambdalayer:latest .
            docker create --name lambdalayer lambdalayer:latest
            docker cp lambdalayer:/install/python.zip .

workflows:
  version: 2
  build:
    jobs:
      - check-code-style
      - check-docstyle
      - check-twine
      - tests-python:
          name: test-3.6
      - tests-python:
          name: test-3.6-without-ciso8601
          enabled-ciso-8601: false
      - tests-python:
          name: test-3.6-influxdb-nightly
          influxdb-image: "influx:nightly"
      - tests-python:
          name: test-3.7
          python-image: "circleci/python:3.7-buster"
      - tests-python:
          name: test-3.8
          python-image: "circleci/python:3.8-buster"
      - tests-python:
          name: test-3.9
          python-image: "circleci/python:3.9-buster"

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - tests-python
      - check-aws-lambda-layer
